### ISSUE TITLE
I get this error when running script from F360

### ISSUE THREAD

**Issue by eraser3000** [DVE2000/Dogbone#11]
![error](https://cloud.githubusercontent.com/assets/8743378/14235499/5c326a5e-f9bd-11e5-93b7-e17aed82e473.png)

**Comment by caseycrogers** [comment]
Hello eraser,

Did you download the entire zip file from github? If you copy just dogbone.py you will get this error. If you did download as zip and then extract all the contents, then something else is going wrong. If that's the case let me know and I'll try to figure it out.

**Comment by eraser3000** [comment]
Thanks, no I did not download the full Zip, Thanks for the tip I will give it a whirl.

**Comment by eraser3000** [comment]
works good now, sorry I have a lot to learn :) :+1:

**Comment by zebrassimo** [comment]
![1](https://cloud.githubusercontent.com/assets/20027464/16178032/7792a44a-363e-11e6-9228-d70b8ea8a990.PNG)

Having the same issue. The dogbone zip was completely unzipped into the apps folder. After running the script, the icon showed. When clicking on the icon, this messagebox appeared. Clicking ok showed the dialog window but it's not working.

**Comment by MrZinn** [comment]
Casey--I am getting the same error script.  What folder do I unzip the files to?  Here is where I have it now:

C:\Users\MrZin\AppData\Local\Autodesk\webdeploy\production\00acb530044182955dd92b716af43e78c7229309\Api\InternalAddins\Dogbone-master

MrZinn
