### ISSUE TITLE
can't get it to work on fusion 360 version 2.0.2016

### ISSUE THREAD

**Issue by tbbooher** [DVE2000/Dogbone#12]
the dogbones never create. can anyone duplicate?

**Comment by tbbooher** [comment]
I started looking at the code, but haven't been able to troubleshoot it yet. I have made this video, to show what I'm seeing.

https://knowledge.autodesk.com/community/screencast/87c5cbcb-bf33-420e-885a-c4bf7d714b2d

**Comment by BeauTurner** [comment]
I am able to duplicate the issue you showed only when having the inside cutout with a fillet on the corners. Temporary workaround, remove the inside cutout, run dogbone then add the inside cutout as a cut operation. 
<img width="534" alt="screen shot 2016-05-15 at 9 50 37 am" src="https://cloud.githubusercontent.com/assets/1288735/15274549/911b9674-1a82-11e6-8759-f9153ee7435c.png">

**Comment by tbbooher** [comment]
Will try -- I would like to get the plugin working in debug mode so i can troubleshoot this and help contribute. Any tips on that?

**Comment by tbbooher** [comment]
any tips on how to remove the inside cut out -- i can do it, but it is a long and difficult process

**Comment by tbbooher** [comment]
Actually, I removed the void and the error persisted.Still don't have an error, just the options disappear. At this, point, I'm thinking of writing a more basic script that only works on a segment, or just manually adding the dogbones.

**Comment by BeauTurner** [comment]
Can you start simple. Sketch the same outside shape as you have now. Run
the Dogbone script. Does it work?  If so then edit the sketch (or create a
new one) and add your inside, then extrude and cut into your shape you have
with the dogbones placed.

-Beau

On Tue, May 17, 2016 at 9:50 AM, Tim Booher notifications@github.com
wrote:

> Actually, I removed the void and the error persisted.Still don't have an
> error, just the options disappear. At this, point, I'm thinking of writing
> a more basic script that only works on a segment, or just manually adding
> the dogbones.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/caseycrogers/Dogbone/issues/12#issuecomment-219723455

## 

-b

**Comment by caseycrogers** [comment]
Hey guys, I'm sorry dogbone is giving you trouble. I can take a look at the add-in in a couple hours and see if I can figure out what's going on.

Typically when the options disappear it's because the dogbone failed to exit properly. Can you send me a .f3d file of the part giving you trouble? You can post it here or e-mail it to me at caseycrogers@berkeley.edu.

**Comment by caseycrogers** [comment]
The issue appears to be that the add-in is trying to make dogbones at the edges of the fillet. I'm working on a fix for it now, however in the mean time you can use the dogbone add-in to select specific edges (and not the whole body) to manually choose which edges to apply the fillet to.

**Comment by tbbooher** [comment]
hmm. . . manually picking edges doesn't work for me. I'm happy to try another approach or help troubleshoot.

**Comment by tbbooher** [comment]
I'm coming back into my projects, curious if there has been any update for this. Thanks.
