### ISSUE TITLE
New dogbone doesn't work on initiation

### ISSUE THREAD

**Issue by tbbooher** [DVE2000/Dogbone#16]
When I try to run it, I get:

```
F Fusion 360 X 
Failed: Traceback (most recent call last): File *ClUsers/tim_000/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbonelotils.pf, line 140, in notify notify_method(args) File -C/Users/tim_000/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py-, line 79, in onCreate adsk.core.ValueInput.createByString(self.circStr)) File -C/Users/tim_000/AppData/Local/Autodesk/webdeploy/production/9400 line 3944, in addvaluelnput return _core.CommandInputs_addValueInput(self, *args) RuntimeError: 2 : InternalValidationError : input->evaluateString(xlVal->valueAsIString(), dTemp, bValueStrChanged) 
```

I'm using fusion 360 2.0.2088 on Windows 10.

Happy to email the file as needed.

You can download my model from this forum link: https://forums.autodesk.com/t5/design-validate-document/can-t-change-appearance/td-p/6382182

**Comment by tbbooher** [comment]
@caseycrogers would you like me to do some more work on this? Your plugin is critical to getting inside corners to work. If you are working it, let me know, otherwise, I'll try and carve out some time this weekend to fix.

**Comment by caseycrogers** [comment]
Hello booher,  I'm sorry I can't be of more help but I'm on vacation this month.

If you want to have a go at it I'd definitely appreciate it and I'll be happy to merge your work with the main branch.

**Comment by tbbooher** [comment]
got it -- thanks

On Fri, Jun 17, 2016 at 7:20 AM, caseycrogers notifications@github.com
wrote:

> Hello booher, I'm sorry I can't be of more help but I'm on vacation this
> month.
> 
> If you want to have a go at it I'd definitely appreciate it and I'll be
> happy to merge your work with the main branch.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/caseycrogers/Dogbone/issues/16#issuecomment-226744818,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAqTvJhHb-u72LK6ggKuSWtFR4pZG8Xks5qMoMJgaJpZM4I1P5h
> .

## 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Tim Booher
www.theboohers.org | tim@theboohers.org
703.649.4264 (home)
(703) 822-7863 (mobile)

**Comment by ThreepE0** [comment]
I'm having the same issue, same exact error message.  I'll keep an eye out for a fix.  Hope you had a great vacation, thanks for the work on the add-in.

Update: I changed Dogbone.py line 28 from ' self.circStr = "cutter" ' to ' self.circStr = "0.25 in" ' and the issue resolved.  Looks like the default value of "cutter" was throwing things off
