### ISSUE TITLE
How to solve traceback issue

### ISSUE THREAD

**Issue by yeowooh** [DVE2000/Dogbone#18]
![untitled](https://cloud.githubusercontent.com/assets/20502989/16901442/701ed550-4c76-11e6-82da-de371bba82b9.jpg)

**Comment by ThreepE0** [comment]
open Dogbone.py.  line 28 has a default value of "cutter."  change it to something like "0.25 in" and you should be good to go.

before:
self.circStr = "cutter"
after:
self.circStr = "0.25 in"

worked for me.  hope this helps.

**Comment by ThreepE0** [comment]
I noticed there were a few issues opened for this same thing, so I created a pull request

**Comment by yeowooh** [comment]
solved........thank you very much

**Comment by yeowooh** [comment]
just for the info for those newbies like me.
To change the value for the cutter , you will need to change it from the debug menu.

**Comment by UncleGravity** [comment]
@OceansCrashing I set self.circStr = "0" and it fixed the first issue.  So it loads the dialog without the traceback, thanks for the tip.

Not sure if this happens to anyone else but if I try to run the script on a simple test figure, it fails.

First image is when I click on the solid body:
<img width="1085" alt="screen shot 2016-07-27 at 5 20 54 pm" src="https://cloud.githubusercontent.com/assets/1423511/17193659/15c91eae-5422-11e6-992c-47fcb397bfaa.png">

Second image is when I select the edges:
<img width="1098" alt="screen shot 2016-07-27 at 5 51 07 pm" src="https://cloud.githubusercontent.com/assets/1423511/17193813/c4ef99ee-5422-11e6-8812-45b91aeec92a.png">

I'll try using the debugger to figure it out, but if anyone knows what's up, let me know.

**Comment by UncleGravity** [comment]
Nevermind, I had the axes wrong.  I always thought "top" was the z axis.  Guess I was wrong.  Cheers.

**Comment by jbold** [comment]
The above fix isn't working for me. Still getting multiple traceback errors:
![screen shot 2016-08-11 at 7 46 36 pm](https://cloud.githubusercontent.com/assets/374123/17609620/6458ca48-5ffc-11e6-906b-dc04df2d8301.png)

**Comment by jbold** [comment]
Found a workaround - this older version doesn't have the bug - https://github.com/tapnair/Dogbone. I can only select edges though, and have to use a numerical tool diameter ex "0.375" vs the param "cutter"

**Comment by DrProv** [comment]
Hi,  I just had the same issue after installing DogBone.

UncleGravity above had the correct fix for me.  It was user error in not selecting the correct axis.

UncleGravity said:
Nevermind, I had the axes wrong. I always thought "top" was the z axis. Guess I was wrong. Cheers.


Thanks so much for this solution.  This was my first time using the addin and looks awesome.
