### ISSUE TITLE
Doesn't work correctly with tabs that aren't the full thickness of the material.

### ISSUE THREAD

**Issue by chmedly** [DVE2000/Dogbone#22]

**Comment by chmedly** [comment]
Did I just hit enter accidentally? ;) 

Anyway, I'm finding that more often than not the circle gets drawn on the wrong side of one of the lines.  I've been correcting this by editing the sketch and simply mirroring the circle to the opposite of the "protruding line" but this takes time AND, the resulting fillet doesn't actually go all the way through the material.  If I were milling with some kind of double sided capabilities this might be nice but in most cases were doing all milling from one side of the material so the tool needs to cut through the entire thickness of the material.  My solution has been to do a drilling operation using the dogbone fillets to define the location of the drills.  Again, this takes extra steps.  I'm not sure this is easy to "fix" but it would be great if someone can figure it out. 

![image](https://cloud.githubusercontent.com/assets/8793863/23970897/a2c36378-0999-11e7-9f4e-800e390b40c5.png)
![image](https://cloud.githubusercontent.com/assets/8793863/23970914/ad03591a-0999-11e7-99ac-80a32aa8aabc.png)
![image](https://cloud.githubusercontent.com/assets/8793863/23970921/b2e2e120-0999-11e7-8fc8-604200bcc7ce.png)
![image](https://cloud.githubusercontent.com/assets/8793863/23970927/bb14ba12-0999-11e7-9699-3617bf1f192e.png)

**Comment by cweber9843** [comment]
Not a fix for the wrong side of the circles, but a possible fix for being able to mill from one side: If you edit the extrude created by the dogbone plugin, you can choose to make it e.g. symmetric, so it will cut through the whole material. 
![image](https://cloud.githubusercontent.com/assets/27760408/26286613/cb0db6b2-3e69-11e7-98da-30eccb344c77.png)
But I would also like to have the circles placed on the outside, I can confirm that they are misplaced when the edge does not go all the way through the material. So my workaround for this is to create 2 bodies, one with the fingers, one without on top of it. Then I place the dogbones on the one with the fingers and join them afterwards. 
Another workaround, but might be less work when you have many fingers?

**Comment by knickels** [comment]
I'm seeing this same behavior even on full-thickness tabs.  There is a sliver of material left on one edge.  If that edge happens to be on the profile you select for CAM, it cuts a square hole!  

I had to set the extrude extent to "all" rather than "distance" to get the doggone to go all the way through the material.

**Comment by pludikar** [comment]
@cweber9843 @chmedly @knickels 
Try downloading/pulling the new version - new version should have resolved this issue.  Let us know how you get on.

Peter
