### ISSUE TITLE
RuntimeError: 3 this is not a parametric design

### ISSUE THREAD

**Issue by tarchive** [DVE2000/Dogbone#24]
Windows 10 PC .

Open Fusion 360.
Insert>Insert Mesh>pick any Thingiverse STL.
Right click Document settings>Do Not Capture Design History>Continue.
Modify>Mesh>Mesh to BRep> select mesh body > OK.
Go to Patch>Modify>Merge>Select Chain>select top face>OK.
Go to Model>DOGBONE> set tool diameter > select any interior edges or faces > use any settings > OK > Error.

![error 3](https://user-images.githubusercontent.com/26031707/30008672-d5e772e8-90ef-11e7-8a67-45a4d26f5613.PNG)

Any combination of DOGBONE settings result with shown error.
Any combination of selected interior edge, edges, or solid bodies result with error.

**Comment by prosoftJit** [comment]
Looking at the code, I discovered that this error happens if you're not capturing design history (Do Not Capture Design History)
Dogbone.py line 176 is "startIndex = self.design.timeline.markerPosition" <- error

**Comment by tarchive** [comment]
Thanks for contributing! Unfortunately you just reworded and "discovered" something in this error message that would be obvious to someone with any coding or debug knowledge. I am not trying to discourage you from helping but i am just disconcerted because i thought i had provided a clear and simplified submission.

I do not have programming knowledge in python, nor do i care to learn, but with my knowledge in other languages I can assume if the operation of DOGBONE relies on having Capture Design History enabled then this is not going to be a simple fix, if it is even worth fixing at all.  

To anyone else wondering, the reason I must select "Do Not Capture Design History" is in order to get the "Mesh to BRep" option. The procedure described in my first post is currently the only reliable way i found to import existing STL models without Fusion360 corrupting the import and causing problems later in CAM. 

Though i am still able to work by manually creating the dogbones. I do welcome alternatives or suggestions.

**Comment by pludikar** [comment]
@tarchive @prosoftJit 

Try downloading/pulling the new version - new version should have resolved this issue.  Let us know how you get on.

Peter
