### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by roontoon** [DVE2000/Dogbone#28]
New to this script. Just downloaded the zip and installed. Getting error in graphic.
![dogboneerror](https://user-images.githubusercontent.com/874090/36569688-be17c03e-17fc-11e8-84f9-91eaa10fca3c.jpg)

**Comment by DVE2000** [comment]
Interesting. Apparently you don't have write permissions in your own home folder. You may want to use Finder or terminal to see why that happens. I put the file write in a simple exception handler and pushed a new version to github for you. The defaults write will fail silently for you, but at least you'll be able to run dogbone.

**Comment by roontoon** [comment]
Not sure where the file is. In terms of writing to my own home folder, I have no issues with that other than this script. Do you have a more specific location that I can look into? Thanks.

**Comment by roontoon** [comment]
Everything with in API was writeable by me plus I changed everybody to read/write and included all enclosed files and folders. Same behavior. Not sure where you put the new zip file. 
![dogbone2](https://user-images.githubusercontent.com/874090/36572148-301635e8-1808-11e8-92d5-a63c5b685a0f.jpg)

**Comment by DVE2000** [comment]
Look at at the last line of the traceback you posted. It said there was a permission error writing the defaults file. Very weird. And it shows the path to your Dogbone folder. You can just copy the new Dogbone.py file into that folder. Worst case, it won’t remember your last setting. I have no idea why there would be a permissions error.

**Comment by roontoon** [comment]
I originally was having an issue with apparently another version of dogbone. I found your github and downloaded the current version and then started this thread. I can get the new version to run but it does not build the dogbone. In the attached video you will see dogbones that were made by the previous version and what happens when I try just one. 
[dogbone.mp4.zip](https://github.com/caseycrogers/Dogbone/files/1750222/dogbone.mp4.zip)

**Comment by DVE2000** [comment]
Wonderful. :( Do you see a folded timeline at the end for the dogbone? Do you have a dogbone sketch created at least? You could also try unselecting the "Unconstrained" option. It uses a slightly different code path.

**Comment by roontoon** [comment]
Just did it.... Nope.
[dogbone2.mp4.zip](https://github.com/caseycrogers/Dogbone/files/1750299/dogbone2.mp4.zip)

**Comment by roontoon** [comment]
Don't know if this will help you but here is a link to the file that I am using dogbone on. Please excuse any stupid newbie mistakes. Just learning Fusion360.  http://a360.co/2sKXEgf

**Comment by DVE2000** [comment]
Could you please attach an exported archive of that here? The autodesk site is emailing me links for .dms files, when I'm selecting fusion 360 archives.

**Comment by roontoon** [comment]
There you go. Thanks for the help on this.
[DogboneProblem.zip](https://github.com/caseycrogers/Dogbone/files/1752406/DogboneProblem.zip)

**Comment by DVE2000** [comment]
I selected one edge, and tried to create a dogbone on it, with the "Output Unconstrained Geometry" selected. There's something strange with the underlying sketch. If you look at the timeline, you'll see a dogbone circle was created, but the extrusion wasn't. I turned on the lightbulb for the dogbone sketch, selected the circle, and then tried to extrude. This is what happened:
<img width="1245" alt="screen shot 2018-02-23 at 12 10 07 pm" src="https://user-images.githubusercontent.com/7603932/36624378-6c801bdc-18dc-11e8-8cb0-d5f95b7ecf91.png">
If I select "Capture Position", I can extrude the circle and cut the dogbone. If I select continue, the circle is moved. Like this:
<img width="679" alt="screen shot 2018-02-23 at 12 10 22 pm" src="https://user-images.githubusercontent.com/7603932/36624393-9c40067a-18dc-11e8-84e9-7bccb674257a.png">

If I deselect the output unconstrained geometry option, It actually does cut dogbones (VERY slow) but they're not cut to full height!
<img width="1176" alt="screen shot 2018-02-23 at 9 11 13 pm" src="https://user-images.githubusercontent.com/7603932/36624538-79627456-18de-11e8-9ad8-5d8123ba389d.png">

Why? No idea. I'm relatively new to Fusion as well. And the API is buggy. Dogbone isn't as robust as I'd like, but I'm busy working on some solutions with someone.

One think I have learned is that you should probably create a new component for every piece you're making, and put the sketches and bodies in that.

I wish I could be of more help...

**Comment by roontoon** [comment]
Well, I got it working sorta. I deleted all previous attempts at creating dogbones and tried again. Selecting individual parts as bodies at first and that went well until I started selecting drawer sides and backs. It would always throw an error. I then started selecting the individual edges that needed dogbones on one end of the piece and found out that I was getting a consistent error when selecting an entire end. In the graphic below if I selected edge A along with the longer edges B it would error out. If I only selected edges B on the entire body it would create the dogbone. If I selected only edge A on the body then it would create the dogbone. Anytime I attempted to combine the two different edge lengths the script would crash. Thanks for your help and I hope this helps you track down this issue. 
![dogboneproblem](https://user-images.githubusercontent.com/874090/36624508-24f05dac-18de-11e8-9bd4-ed68bacb9f9c.jpg)

**Comment by DVE2000** [comment]
I'm glad you got something working. There's definitely an issue with having to have cuts of different heights. I tried to come up with a solution for that, and Fusion started crapping out on me.

**Comment by caseycrogers** [comment]
As a note on the "Capture Position" error:
In Fusion when you have a component it can be dragged freely in 3D space. Try clicking and dragging on a component and you'll see it moves. When it moves from its original position, Fusion won't let you perform any more operations until you either:
A) save the new position or
B) revert to the initial position
Generally, if you're not intending for a component to move, you should right click on it in the browser and click "Ground" which will lock it in place. I personally only ever create components when I intend to have the interact with other parts (ie joints). But a lot of that is personal preference.
It's understandable that DogBone would fail in this context-though really there should be an informative error message.
