### ISSUE TITLE
Incorrect dogbone direction on multi-depth model corners

### ISSUE THREAD

**Issue by jinschoi** [DVE2000/Dogbone#29]
I'm trying to dogbone a pocket corner, and the add in is putting the dogbone at the wrong angle:

<img width="369" alt="screen shot 2018-03-11 at 12 02 17 pm" src="https://user-images.githubusercontent.com/938840/37255547-68dab236-2524-11e8-9f0e-008af1b57b28.png">

I can go in and fix this by adjusting the angle in the sketch created when generating parameterized dogbones. Here's what it should look like:

<img width="237" alt="screen shot 2018-03-11 at 12 08 41 pm" src="https://user-images.githubusercontent.com/938840/37255607-0011b5fa-2525-11e8-937e-cf4281bc96ea.png">

Here is my test example for the above:

[dogbone-test.f3d.zip](https://github.com/caseycrogers/Dogbone/files/1800544/dogbone-test.f3d.zip)

**Comment by DVE2000** [comment]
Funny things happen with non-full height edges.  I don’t have time to look it at right now, unfortunately.

**Comment by pludikar** [comment]
@jinschoi 

Try downloading/pulling the new version - new version should have resolved this issue.  Let us know how you get on.

Peter
