### ISSUE TITLE
Runtime error 3 at startup of the script

### ISSUE THREAD

**Issue by roontoon** [DVE2000/Dogbone#31]
Get this runtime error at startup of the script. Was working. Have updated Fusion a number times so no help there.

<img width="516" alt="error" src="https://user-images.githubusercontent.com/874090/44179370-77475d80-a0c4-11e8-8024-884d540e9120.png">

**Comment by DVE2000** [comment]
Looks like something happened to the Resources folder? But that path of yours looks wrong. Dogbone.py should be in ..../API/Dogbone/Dogbone.py. Not the Scripts directory. And the resources folder should be in ..../API/Dogbone/Resources.

**Comment by roontoon** [comment]
Thanks
