### ISSUE TITLE
Dogbone works on one panel but not selected others.

### ISSUE THREAD

**Issue by roontoon** [DVE2000/Dogbone#32]
Not sure what the issue is but I select all parts that are on one piece of plywood but several do not apply doggone. See pic.
<img width="668" alt="dogbone" src="https://user-images.githubusercontent.com/874090/44687665-c922a880-aa1f-11e8-9a2d-81bc07380062.png">

**Comment by DVE2000** [comment]
It can be buggy. I’ve been helping someone with a new version. 

 Have you tried with and without parameterization? What happens if you just select an edge of one of these mortises that don’t get dogbones?

**Comment by roontoon** [comment]
Selected only the four vertical edges of the pic above and nada.
<img width="1021" alt="dogbone2" src="https://user-images.githubusercontent.com/874090/44748202-2df00880-aadd-11e8-9154-ccc092ae15cc.png">
<img width="658" alt="dogbone3" src="https://user-images.githubusercontent.com/874090/44748213-32b4bc80-aadd-11e8-8553-5cc80700c724.png">

**Comment by roontoon** [comment]
Any thoughts on how to solve this?

**Comment by DVE2000** [comment]
Sorry, been busy. Are the sketches created? You'd have to click the lightbulb to see. You could try increase the angles, but that shouldn't matter. Unconstrainted vs constrained? Otherwise you'll have to let me run the debugger with your design.

**Comment by pludikar** [comment]
@roontoon 

version 2 of dogbone has been released.  This should have resolved this issue (among others).  Please download/pull the new version and let us know how it goes.

Peter
