### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Marmess** [DVE2000/Dogbone#35]
Hi,
I am having this error.
Any idea how to debug this?
Thanks!
M

<img width="403" alt="screen shot 2019-01-17 at 11 12 12 am" src="https://user-images.githubusercontent.com/46789941/51332207-4ab7b900-1a49-11e9-8ca9-63807ea05e51.png">

**Comment by pludikar** [comment]
Hi @Marmess 

You need to have history activated.  Click on the topmost item in the design browser.  You’ll find the choice to activate/deactivate history at the bottom of the drop down.

Get back to us if that didn’t work.

Peter

**Comment by Marmess** [comment]
Deat Peter,
Thanks for your answer.
But it looks like my history is activated looking at this preference.
M

**Comment by pludikar** [comment]
Hi @Marmess 

I can get the exact same error message if my history timeline is turned off.  To confirm that you have history timeline activated: You should see playback buttons at the bottom left of your f360 screen, and there should be a series of timeline events shown to the right of the playback buttons. There should also be a grey bar along the bottom with a setup gear icon on the right.  When you right click on the component browser you should see the capture Design History entry: 

![history activation](https://user-images.githubusercontent.com/4363084/51364889-ad41a100-1aab-11e9-894f-0dbd1430a709.png)

These are the playback buttons that should be visible on the bottom left of your F360 screen.
![history buttons](https://user-images.githubusercontent.com/4363084/51364942-de21d600-1aab-11e9-8201-7bfb2e869d28.png)

If you definitely have the history timeline on, then there is another problem.  The easiest way to solve that is create a screencast and record the actions you take to get the error [see here](https://knowledge.autodesk.com/community/screencast) - then post me the link, so I can see what you are doing.

Peter

**Comment by Marmess** [comment]
A thousand times thanks for this! Really awesome!
All the best,
M
