### ISSUE TITLE
DOGBONE FAILD FUSION 360

### ISSUE THREAD

**Issue by EliaAJG** [DVE2000/Dogbone#37]
Hi, this is the first time I m writing in a forum. I have a problem with the Dogbone Add-in. It keep failing and I do not understand way. I Downloaded from here : https://github.com/DVE2000/Dogbone and installed as it says. 
Here is some screenshot.
Do anyone knows the reason?;-)
![faild](https://user-images.githubusercontent.com/47451962/52481594-392c8180-2baf-11e9-8f32-42051b087cc0.JPG)
![capture_01](https://user-images.githubusercontent.com/47451962/52481603-3df13580-2baf-11e9-8d4e-15156d746c8a.JPG)

**Comment by pludikar** [comment]
Hi @EliaAJG 

The reason for this, almost certainly, is that you need to have history enabled in F360.  See [here](https://github.com/DVE2000/Dogbone/issues/35) for a thread where the same issue was reported.  Let us know if that helps.  We'll be happy to help further if there are still problems or issues.

Regards
Peter

**Comment by pludikar** [comment]
Hi @EliaAJG ,

Just so you know - I've added a check into the code to ensure that you are in Parametric mode.  You can install the latest file - but you will need to install manually. 

1.  Get zip file by clicking green button  labelled "Clone or Download" on Github main code page [here](https://github.com/DVE2000/Dogbone), then 
2. click on 'Download Zip'. 
3.  Follow instructions [here](https://github.com/DVE2000/Dogbone/releases)

However, note that you will be the guinea pig for the code update - it should work, but let me know if you have any issues.

Regards
Peter

**Comment by EliaAJG** [comment]
Dear Peter,


Sorry for the late answer. Thank you very much for your support, I will certainly contact you again in case of further problems.
med venlig hilsen/ kind regards

Elia Giampellegrini


architect
AJG Architects
direct +45 61 68 8 966
Nyhavn 63B, 2. Sal., 1051 Copenhagen K, Denmark
<office@aj-da.com>






Confidentiality Note: The information in this electronic mail message may be confidential and for use of only the named recipient.

The information may be protected by privilege, work product immunity or other applicable law. If you are not the intended recipient
the retention, dissemination, distribution or copying of this e-mail message is strictly prohibited. If you receive this e-mail message
in error please notify us by e-mail at<office@aj-da.com>






Den 8. februar 2019 kl. 17.52.57 +01.00, skrev Peter Ludikar <notifications@github.com>:

**Comment by EliaAJG** [comment]
Dear Peter,

I have just installed it and it works. Thank you again for you help and time.


med venlig hilsen/ kind regards

Elia Giampellegrini


architect
AJG Architects
direct +45 61 68 8 966
Nyhavn 63B, 2. Sal., 1051 Copenhagen K, Denmark
<office@aj-da.com>






Confidentiality Note: The information in this electronic mail message may be confidential and for use of only the named recipient.

The information may be protected by privilege, work product immunity or other applicable law. If you are not the intended recipient
the retention, dissemination, distribution or copying of this e-mail message is strictly prohibited. If you receive this e-mail message
in error please notify us by e-mail at<office@aj-da.com>






Den 10. februar 2019 kl. 01.37.09 +01.00, skrev Peter Ludikar <notifications@github.com>:

**Comment by Dutchy-79** [comment]
Got the same error while running version 2.0
I don't see a manual to install another version.

**Comment by pludikar** [comment]
Hi,
Would it be possible for you to make a copy of your model available?  It’s unusual for the dogbone app to fail, unless there’s a problem with the underlying model.  As much as I like it, unfortunately F360 has tons of bugs that cause models to break easily.

A screenshot, or two of the app in action would be useful too.

I’m working on an upgraded version, that should bypass several of the f360 shortcomings - however, it may take a while before that’s available.

Regards
Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
