### ISSUE TITLE
Allowing some tolerance for "almost acute angles")

### ISSUE THREAD

**Issue by romlel** [DVE2000/Dogbone#42]
Hello
Your addin save my life evey day, I use it all the time for CNC wood jointery ! Thanks a lot.

Recently, I extruded some shapes to cut and I used Dogbone to make it machinable, but because the shapes came from an approximate vector graphics source, with lots of polyline and no real splines, I have some extra points on lines that are slightly misaligned and cause some angles around 179~180 degrees that Dogbone detect

So, or course, as soon as an acute angle is found - event slight, Dogbone select it, and suggest to process lots of "unnecessary" edges (that should never have been on my shape in the first place, but I couldn't optimize the shape easily)

I hacked a little the code by adding a tolerance and it would solve this particular case. After all, when using polylines and not splines, some Epsilon is to expect in the angle calculation.
For tests, I made something like : 
if dbUtils.getAngleBetweenFaces(edge) > math.pi - 0.2: 

I'm not good at Python and failed to try to change your UI. Would it be possible to add an option for a tolerance parameter ? Either as a subtraction like I tried, or even a multiplicative factor (only process angles lower than 0.8 * Pi, so only the very "sharp" turns are processed - after all jointery is 30/45/60/90 degrees most of the time, the rest could stay as it is as an option (just artistic shape, no need for dogbones)

What do you think ?
Thanks !

**Comment by pludikar** [comment]
Hi,

Thanks for your comments - really pleased that the addin has been useful to you.

I’m actually working on a new version of the addin that not only adds the tolerance, but also will cut appropriate dogbones into acute and obtuse angles.  The basic mechanism has already been coded and works very nicely, but I’m also adding the ability to edit and refresh any dogbones that have already been added - this is taking longer than I anticipated, but I am making progress.  I can’t make any promises on how long it will take, but it is definitely being worked on and hopefully it won’t take too much longer.  I’ll let you know when the beta version is ready.

Regards
Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chriscairns** [comment]
I also find your plugin extremely useful for CNC projects so many thanks for developing it!

**Comment by romlel** [comment]
Thanks for the details. Very good news you continue to add features !
I'll keep my "ugly tolerance hack" in my working copy for now waiting for the next big release, and be happy to test the beta and provide tests & feedback !

Best regards
