### ISSUE TITLE
Can't find Dogbone icon?

### ISSUE THREAD

**Issue by tiktuk** [DVE2000/Dogbone#44]
Hi, from where should Dogbone be run? I can't see the icon anywhere after installing and running the Addin. I only managed to run it from the command box (the one that shows up when pressing "S").

**Comment by pludikar** [comment]
Hi @tiktuk,

Sorry for the delay in responding - it's been a busy day. 

You'll find the addin icon under the SOLID tab at the right hand end of the CREATE panel, in the DESIGN workspace.  You'll also find the dogbone command under the CREATE pulldown at the very bottom.  I hope you find the addin useful. See here:
![image](https://user-images.githubusercontent.com/4363084/64833942-ecc67b80-d5ad-11e9-9985-e6a63dab00f1.png).  

Regards
Peter

**Comment by tiktuk** [comment]
> Sorry for the delay in responding - it's been a busy day.
> 
> You'll find the addin icon under the SOLID tab at the right hand end of the CREATE panel, in the DESIGN workspace. You'll also find the dogbone command under the CREATE pulldown at the very bottom. I hope you find the addin useful.

Thank you! It is very useful indeed, thanks a lot for your work ☺️ .

Tuk
