### ISSUE TITLE
DogBone fail when a body contains an inner fillet/ slot

### ISSUE THREAD

**Issue by FabCreator** [DVE2000/Dogbone#45]
Hi,
Just been using the dogbone addin, its very good. Saves alot of time!
However I discovered an issue when you try and dogbone an entire body, if that body contains a slot or fillet the dogbone will fail.

![image](https://user-images.githubusercontent.com/19230933/73060393-02bb4580-3e98-11ea-87ab-6188a94ecd40.png)

![image](https://user-images.githubusercontent.com/19230933/73060398-064ecc80-3e98-11ea-9a7c-3d86c311191b.png)

![image](https://user-images.githubusercontent.com/19230933/73060552-60e82880-3e98-11ea-9610-582db0b8fa91.png)
![image](https://user-images.githubusercontent.com/19230933/73060561-647baf80-3e98-11ea-9908-c4894cc5e27f.png)

![image](https://user-images.githubusercontent.com/19230933/73060577-6e9dae00-3e98-11ea-9688-9b3832d98812.png)

Deleting the fillets / slots and remaking them after the dogbone operation, or manually selecting the edges are workarounds.
 
Cheers,
Bonne

**Comment by pludikar** [comment]
Hi Bonne,

Thanks for bring this to my attention.  It seems that the fillets and slots don't behave as other edges do, so I'll have to look into that.  

Unfortunately F360 "upgraded" their old spyder IDE to Visual Sudio Code a few months back, and I found a major show stopping bug in their new implementation.  I've spoken to AutoDesk and they've fast tracked the issue.  They included it in their latest sprint cycle, which started last Wednesday, but it could be a month or so before they get the issue fixed.  Until then I'm hampered and not going to be able to do much.

Once AD has fixed the IDE issue I'll get back to you.

Peter

**Comment by pludikar** [comment]
Hi Bonne,
 I know it's been a year - AD and the F360 team have finally resolved the show stopping bug, and I've been able to look at your issue.  Are you still using the dogbone AddIn?  and... if yes, are you still experiencing the same issue?

Peter
