### ISSUE TITLE
Dogbone fails after first edge, even in static mode

### ISSUE THREAD

**Issue by davidhatten** [DVE2000/Dogbone#46]
Hello, 

I have a component and I am attempting to add dogbones to it. When I add static dogbones, it incorrectly creates one dogbone and then fails on the rest. These edges were created from a "Rectangular Pattern" operation, for what it's worth. I've attached the error log. Parametric also fails, but I don't need it to be parametric at this point so I'm not worried about it.

Thanks!

Log:
[dogbone.log](https://github.com/DVE2000/Dogbone/files/4462359/dogbone.log)

**Comment by pludikar** [comment]
Hi @davidhatten 

Would you be willing to send me a copy of your design?  It's not obvious from the log what's causing the issue.  

If you don't want it in the public domain, you can PM me on Fusion 360 and I'll give you my email through that medium.

Note: To create the copy - in fusion go to File then export.  Make sure you are exporting to .f3d (which is the default).

Regards
Peter

**Comment by davidhatten** [comment]
Hello,

Happy to provide, and I don't mind this being in the public domain but thank you for bringing that to my attention, I'm new to CAD and wouldn't have thought of that.
[Holder Flat Pack v6.zip](https://github.com/DVE2000/Dogbone/files/4463442/Holder.Flat.Pack.v6.zip)


Let me know if you need anything else or any details about how this was made. Thanks!

**Comment by davidhatten** [comment]
I just realized, that won't have the sketches used to create any of these features/bodies/components, here's the original design I copied the components from to make the flatpack, in case you need the sketches. Errors also happen in this design.

[Holder Assembled Model v10.zip](https://github.com/DVE2000/Dogbone/files/4463443/Holder.Assembled.Model.v10.zip)

**Comment by pludikar** [comment]
Hi @davidhatten 

I've just had a look at both your models, and they don't show the issue.  I suspect that your model had a corruption somewhere along the process.

However you should note that F360 is very fussy and models do break easily.  There are a number of best practices that would help you keep a stable model (even though that's not a guarantee!).

I would suggest

1. Create two components (an assembly component and a nest component) - this will allow you to keep your assembly and flat pack in the same model, so if you make changes in the assembly it'll reflect directly in the nest.  (having the assembled model and flat pack in different files makes life more complicated than needed - if you have both in the different files, making changes in one means you have to recreate the other, and human nature will make you forget to do one or the other) 
2. Do not create bodies then move them to components.  Activate the Assembly component, then make all the components you think you need at the very start of the model timeline, and they'll be sub-assemblies of the assembly component.  
3. If you need to add components, roll the timeline back to the beginning (after the assembly and nest creation) and then add the new one, ensuring that the new component is a sub-assembly to the assembly component.
4. Activate the component before you create the body of that component (you do that by either right clicking the component in the browser tree then select activate, or if you hover over the component in the tree, a circle appears to the right of the component name click that circle)
5. Use joins to keep the components together (this will ensure that if you change parameter values, everything will stick together) 
6. Don't cut mortises in both joining components - make them on one component and then, combine that modified component with the other component (make sure you tick the keep tool box).  This way you'll minimise any errors - e.g. if you do dovetail pins in one side the other side will naturally form the tails after combining.
7. Once the Assembly is complete, select all the components, copy them.  Select the Nest component and paste.  You have to be careful to ensure that you do not copy the whole assembly, in particular, the joints.
8. After the Nest component is populated, make the assembly component invisible (click on the eye next to the assembly component in the browser tree).  This is avoid confusion between the fully assembled model and the components you are going to nest.  You can easily go between Assembly and Nest by making one or the other invisible.
9.  I use an addIn created by Patrick Rainsberry called nester [here](https://github.com/tapnair/NESTER) that helps put all the components onto the same plane, and allows you to move them around to get the best flat pack configuration.  I personally use joins to space and align the components to each other, and one of the components to a stock piece that I create to show me how the pieces relate to the stock.  Makes it easier to create the machine setups in the manufacture workspaceof F360.

I hope I haven't overwhelmed you - I've recreated your model using the practices I've outlined above - see attachment.  Let me know if that has helped.

One last thing: If you key Shift-N in F360, it will toggle the component colour cycling.  This is a great help in keeping your components and actions on those components in order.  The colours of the components will match the colour bars above the timeline events at the bottom of F360.  Ideally you should have single colour bars indicated in each timeline event - sometimes it doesn't work out, but it should help.

Regards
Peter

[Holder - best practice example v2.zip](https://github.com/DVE2000/Dogbone/files/4463821/Holder.-.best.practice.example.v2.zip)

**Comment by davidhatten** [comment]
Wow, thanks a lot for all the tips! I'm still figuring out how to hold F360 the right way (as you can tell!) and this will really help me pivot from "just get the tool to make the thing I imagine" to "get the tool to work right". At most I was doing one of those things (the automatic mortise cutting) so I can totally see how things could get in a bad state. Thank you for the example, and I'll definitely start treating the organization/history as less of an afterthought. If nothing else, remaking it "correctly" is a good excuse to keep practicing at the basics of 3d CAD.

I'll mark this closed, file under "user error" :P
