### ISSUE TITLE
Problem running Dogbone2

### ISSUE THREAD

**Issue by mrfugu** [DVE2000/Dogbone#48]
Hello, 

I recently 'upgraded' this from the original dogbone project (which works well enough) and am running into this error when invoking the new dogbone from within Fusion360 (MacOS): 

<img width="406" alt="Screen Shot 2020-07-08 at 11 19 30 AM" src="https://user-images.githubusercontent.com/29284448/86937379-2b18c280-c10d-11ea-89be-4b46b270d180.png">

Any assistance would be greatly appreciated. 

Many Thanks for creating a very helpful little script.

**Comment by pludikar** [comment]
Hi @mrfugu ,

It looks like your dogbone app is missing some resources (icon files). Try going to %appdata%\Autodesk\Autodesk Fusion 360\API\AddIns\Dogbone2\Resources  you should see a number of directories - fromFace; fromTop; hidden; minimal; normal; parametricMode and staticMode.  Each directory should then contain a number of files usually along the lines of 16x16-disabled.png.

If you don't see those, or you get an error finding the directory - then something went wrong with your installation.  If you're up to doing the installation by hand, then you'll need to find the relevant directories on github and put them in the right place on your computer.  Alternatively there's an installation file [here](https://github.com/DVE2000/Dogbone/releases/download/v2.0/winsetup_Dogbone_v2_0.exe) which should do everything for you.

If you still have issues, please get back to me and I'll help.

Peter

**Comment by mrfugu** [comment]
I have the required Resources folder, and its contents. but I see that it's case sensitive and called 'resources' in the script.. 

find and replace and its good to go! .. 

thanks!!

**Comment by pludikar** [comment]
Hi @mrfugu ,

It looks like your dogbone app is missing some resources (icon files). Try going to %appdata%\Autodesk\Autodesk Fusion 360\API\AddIns\Dogbone2\Resources  you should see a number of directories - fromFace; fromTop; hidden; minimal; normal; parametricMode and staticMode.  Each directory should then contain a number of files usually along the lines of 16x16-disabled.png.

If you don't see those, or you get an error finding the directory - then something went wrong with your installation.  If you're up to doing the installation by hand, then you'll need to find the relevant directories on github and put them in the right place on your computer.  Alternatively

**Comment by pludikar** [comment]
hi @mrfugu 

Glad you got it sorted.  Interesting that, for some reason, my machine isn't case sensitive, and therefore never noticed the difference between Resource and resource

Peter

**Comment by pludikar** [comment]
@mrfugu 

It looks like you have case sensitive directories enabled.  I believe that Windows tends to make insensitive as the default.  Anyway I'll get that fixed in the next update, so it doesn't become an issue in the future.  Thanks for finding that, sorry for the glitch.

Peter

**Comment by mrfugu** [comment]
No sweat, I think its a function of Apple's (relatively new, '18-'19) AFS filesystem here. That said, I'm sure it's good practice to have all the cases match.. 

Love this little timesaver of ya'lls, please count my vote of encouragement for continued development!

**Comment by pludikar** [comment]
I was working on the next iteration - then AD/F360 decided to change the Spyder development platform to Visual Studio Code.  In principle a better way to go - but only if it works!  Unfortunately the F360 team missed the mark and it's presently impossible to create anything more than the simplest script (no file hierarchies, as python expects).  So, until AD fixes that, I'm either stuck with a very long winded way of developing code, or I have to wait.  I've opted to wait.  

I've been talking with AD, but with COVID they're pretty much unable to address the problem at the moment.

For the time being, the AddIn works pretty well and consistently (other than parametric on component copies and mirrors - it's an F360 bug not the AddIn). The next version is going to have dogbones working on corners at angles other than 90, and it is going to be very much faster.  I'm going to use a totally different approach.  Ah well, let hope this pandemic is resolved soon, then I can get back to programming this.

Regards
Peter

Peter

**Comment by mrfugu** [comment]
thanks for the status report. I'll point out that it would be reasonable to expect some form of compensation for a more complete implementation. 

I know there's more than a few BOM, specialized vector types, file compatibility/conversion scripts etc. that are offered by various non-autodesk entities for sale. I don't know the particulars but I'd expect it'd make it worth its while to some degree. I expect theres a large market of Fusion360 users that aren't as savvy with a script as they are handy with a $20 bill. (myself included!) 

Either way, many thanks for the updates and insight for the simple solution. 

Cheers!
