### ISSUE TITLE
Dogbone failure

### ISSUE THREAD

**Issue by beachbumpete1** [DVE2000/Dogbone#49]
I have been using this app for awhile now and it always works great. However yesterday when I tried to use it on a similar part it gives a failure dialog that I cannot copy and paste here.  It says:

Failed:
Traceback (most recent call last):
File "C:/Users/etc etc
Fusion 360 /API/Addins/Dogbone\dbutils.py", line 174, in notify 
notify_method(args)
File...etc
Fusion 360/API/Addins/Dogbone/Dogbone.py", line 644, in onExecute
self.createParametricDogbones()
File...etc
Fusion 360/API/Addins/Dogbone/Dogbone.py", line 851, in
createParametricDogbones
    self.logger.debug(Processing edge-
{}'.format(SelectedEdge.edge.tempId))
File...etc.    /webdeploy/production/d2d901e2ef5ae5c384b4as001a48c4e37589dc43/Api/Python/
packages\adsk\fusion.py", line 4763,in_get_tempId
   return _fusion.BRepEdge__get_tempId(self)
RuntimeError: 2 : InternalValidationError : this ASMEdge

 Not a coder so no idea what this all means but it fails regardless of which or how many corners are attempted to dogbone. It fails every time now. Attempted to delete and reinstall and still fails. Thank you for your efforts on this useful application.  

Pete

**Comment by pludikar** [comment]
@beachbumpete1 

Hi Pete,

It looks like you’re using the addin in parametric mode.  If you try using it in static mode does it work?  Does it also work on some components of the model and not others?  Do you have any components that were created by mirroring?  Does the addin work on a fresh model created from scratch - keep it simple, eg a box with some cutouts?

If it does, it means that you’ve hit a F360 bug that I reported almost 2years ago, and it seems that it’s a more important priority for AD to create new functionality than to solve basic bugs.

Otherwise, can you zip up your model and send it, I’ll then have a look at it.  I’ll guide you on how to do that if you’re not familiar with the process.

Peter

**Comment by beachbumpete1** [comment]
I am sorry I am not sure how to determine what mode I am in. I use it in the design space on a lot of my models and it always works the same way.  Now I try it on any item and it fails. I tried it on different parts. The model is basically a shutter with a mortise and tenon and I am using the dogbone to make inserting the tenon easier.  As far as mirroring parts I create the stile of the shutter using a sketch  for the slats and  pocket for the tenons.  Then I extrude the tenon and slats and use combine to extrude cut the stiles creating the pockets. Then I isolate the stile and use the dogbone command on the face with the pockets. It finds all possible faces and then I manually select the ones I want and hit ok. Then it gives the fail dialog.  I am willing to try whatever helps to determine what is going on.  This is a very useful application for me. 

Pete

**Comment by pludikar** [comment]
Hi Pete,

To select the static mode, click on the button on the left.  Hovering your mouse over the buttons will bring up a brief description.  see below.

![Mode](https://user-images.githubusercontent.com/4363084/90019052-e1774680-dc7b-11ea-9556-58e4e389fd77.png)

Peter

**Comment by beachbumpete1** [comment]
Oh ok thank you.  I thought you meant that fusion needed to be in a particular mode. I just opened a different job and isolated a different part and selected the static mode and it seems to work.  What is the difference?  I tried it on two different parts and it works.  Perhaps that is what was wrong from the start. I never really messed with those selections perhaps I inadvertently selected parametric.  If you select parametric and then say change the dimensions of the pocket in the sketch will it update the dogbones?  I have never tried that. Typically this is the last thing I do to a model before I start the CAM programming.

   Either way this allows me to use the application now again so I am really appreciate the assistance.  Thank you.

Pete

**Comment by pludikar** [comment]
@beachbumpete1 

Hi Pete,

In principle, yes - if you have a model that is driven by parameters, then the dogbones will keep up with any change to those parameters.  However, parametric mode can be quite fussy, unfortunately - as I mentioned before, there are actually several bugs in F360 that AD doesn't seem to want to fix, and using parametric on any model but the simplest tends to hit these inherent bugs and will fail.

Anyway, I'm happy we seem to have got your addin to work again.

Peter

**Comment by beachbumpete1** [comment]
Indeed,  I really appreciate the assistance. I use this quite a bit on our projects.  Much appreciated. Have a great day my friend.
