### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by kroskam** [DVE2000/Dogbone#5]
I have installed the add in to Fusion 360, and it shows up in my add in pulldown in Fusion 360 but I do not have the icon in my create menu or the create pulldown. It shows that it is running, but I am unable to use it. 
Here is the directory that I have it installed in:
C:\users\kevin\appdata\roaming\autodesk\Autodesk Fusion 360\Api\Addins

**Comment by Lander008** [comment]
I have the same issue... i created a folder inside the AddIns folder named dogbone with both files in it - was able to run it from the dropdown menu in fusion and check run on startup, but it never appeared in the list of create functions, and has the circle (pending status?) next ot it.
would be happy if anyone could report if the addin has been working with recent updates of fusion...
(i also get error notifications on startup of fusion: Failed; traceback (most recent call): File "C:/users..../AddIns/Dogbone/Dogbone.py", line 193, in run buttonDogbone = cmdDefs.addButtonDefinition(´dogboneBtn`, ... etc.....return core CommandDefinitions....RuntimeError : 3 : the relative resourceFolder path not found

**Comment by caseycrogers** [comment]
Hello Lander, it sounds like the add-in is having trouble finding some of the files it needs to run.

First, remove the exiting dogbone fold you created. Then, from the github "code" tab, click "download as zip". Open the downloaded zip file and extract its contents to your add-ins folder. This should fix the problem, let me know if it doesn't!

**Comment by kroskam** [comment]
I fixed it by uninstalling and then reinstalling.  

```
On Friday, January 29, 2016 5:09 AM, Lander008 <notifications@github.com> wrote:
```

 I have the same issue... i created a folder inside the AddIns folder named dogbone with both files in it - was able to run it from the dropdown menu in fusion and check run on startup, but it never appeared in the list of create functions, and has the circle (pending status?) next ot it.
would be happy if anyone could report if the addin has been working with recent updates of fusion...
(i also get error notifications on startup of fusion: Failed; traceback (most recent call): File "C:/users..../AddIns/Dogbone/Dogbone.py", line 193, in run buttonDogbone = cmdDefs.addButtonDefinition(´dogboneBtn`, ... etc.....return core CommandDefinitions....RuntimeError : 3 : the relative resourceFolder path not found—
