### ISSUE TITLE
Dogbone isn't applied to Component Body and copies until accessed through history

### ISSUE THREAD

**Issue by davidhatten** [DVE2000/Dogbone#50]
This is an interesting issue that has a workaround.

I have a "template" component that I've copied 4 times. When I attempt to apply dogbones to _any_ instance of _any_ of the sub-components, the dogbone operation appears to fail silently. The operation is present in the history, and when I edit the "hole" part of the dogbone history, everything appears on the body. I modify nothing and just hit "ok", and that's what makes the dogbones take on all instances of the object.

I've followed the more standard workflow instructions you described the last time I had trouble with dogbones and it's been working on other projects, until now.

**Comment by pludikar** [comment]
@davidhatten 

Hi David,

I've experienced this issue myself, and did spend some time trying to figure out what was going on.  I think one of the problems is F360 has made their internal design far more complicated than it needs to be, and as a result, either I have misunderstood one of the programming requirements for applying holes (which I use exclusively in the dogbone add-in) to component copies, or there's a bug in F360.  At the moment I'd give it 50/50 being either.  I know it's a pain, and I will try to find a solution when I can, but I can't promise a timeline at the moment.

Peter

**Comment by davidhatten** [comment]
Hi! 

Thanks for the response, I'm glad to know it's not just me. 

> F360 has made their internal design far more complicated than it needs to be

Oh so it's not just the external design? 😛 

A "feature" to help the workaround might be to allow for multiple sketch selection when defining dogbones (which would then only require a single visit to the history to update everything), but I have no idea if that's actually feasible in-code or how complicated it would be if it is. Ignore that suggestion if it's crazy.

Thanks for the help. Close this, merge it, mark it, whatever you want to do to organize your issue log.

**Comment by pludikar** [comment]
@davidhatten 
Hi David,

Just a thought.  One of things that you can do to save time, is apply the dogbones to the first component (whether in the template or the model itself), then make multiple copies of that, rather than adding dogbones to multiple copies of the same thing at the end.  Once you have copies, in principle, anything you do to the original will reflect into the copies, particularly if you wind the timeline back and do your changes there.

Of course success of that approach will depend on whether you make changes to any of the dimensions.

Peter

**Comment by davidhatten** [comment]
That workflow did work! I'll keep that in mind  going forward, as this isn't the last time I'm going to be doing something like this. Dogboning is usually the last step, so i'll just have to wait to copy out the templates until the very end. Thankfully, every copy is the same except for one panel on the back, and I've already tested the Paste New workflow with a single-subcomponent and that all works. Thanks!
