### ISSUE TITLE
Dogboone contour is not followed in simulation

### ISSUE THREAD

**Issue by askpatrickw** [DVE2000/Dogbone#52]
I'm not sure if this is an issue or maybe just a FAQ on how it works.

My Dogbone's aren't being milled when I look at them in the simulation.

![image](https://user-images.githubusercontent.com/4002194/103045192-70c22e00-457b-11eb-88af-b8ee6266d951.png)
![image](https://user-images.githubusercontent.com/4002194/103045200-76b80f00-457b-11eb-819c-458143238dff.png)

The dogbone is included in the chain I selected.
![image](https://user-images.githubusercontent.com/4002194/103045368-1a092400-457c-11eb-8d95-09f027da0ac8.png)

Tool is .25 diameter
and I'm using defaults pretty much when creating the dogbones.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/4002194/103045455-75d3ad00-457c-11eb-8e72-560f3ef4777b.png">

Is this just a simulation issue or am I doing something wrong possibly?

Thanks!

**Comment by pludikar** [comment]
@askpatrickw 
Hi Patrick,
I've had no issues in simulation, or when I've actually done the cut either.  However, I'm very suspicious of the light blue line that's showing in your screenshots.  It looks like it possibly comes from a sketch and the sketch may have been included in the setup for the model of your operation.  That is, if I'm not wrong (which is always possible).

If the sketch is included in your setup model, F360 will see the line as a boundary and when it tries to go into the dogbone, F360 will prevent it from crossing.

I would suggest editing your setup, delete all the models and then reselect the part(s) that you are planning to cut.  Make sure there aren't any sketches selected for the setup model(s) - easiest is to turn sketch visibility off, so you can't select it by accident.

Then go to your operation and delete the path selection and reselect the bottom of the path (as you have in the last screenshot).

You should be seeing something like the path below.

![dogbone toolpath](https://user-images.githubusercontent.com/4363084/103051315-8f68fa80-4564-11eb-8f4f-4dee9762bfff.png)

If this hasn't helped, the only other way I know is for you to attach your model so I can have a look at it.

Regards
Peter

**Comment by askpatrickw** [comment]
Thanks for the quick response!  I think you're spot on! 
I have a sketch with some text on that part. But another part with no sketch looks more like I'd expect.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/4002194/103066684-468b6300-45b1-11eb-9ef1-2ee3d9b8b398.png">

I'll figure out how to clean it up.

Thanks again!
