### ISSUE TITLE
RuntimeError: 2 : InternalValidationError : face

### ISSUE THREAD

**Issue by Kickjaw** [DVE2000/Dogbone#57]
Failed:
Traceback (most recent call last):
  File "C:/Users/jared/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone\dbutils.py", line 174, in notify
    notify_method(args)
  File "C:/Users/jared/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 644, in onExecute
    self.createParametricDogbones()
  File "C:/Users/jared/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone/Dogbone.py", line 821, in createParametricDogbones
    (topFace, topFaceRefPoint) = dbUtils.getTopFace(makeNative(occurrenceFace[0].face))
  File "C:/Users/jared/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone\dbutils.py", line 121, in getTopFace
    normal = getFaceNormal(selectedFace)
  File "C:/Users/jared/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Dogbone\dbutils.py", line 113, in getFaceNormal
    return face.evaluator.getNormalAtPoint(face.pointOnFace)[1]
  File "C:/Users/jared/AppData/Local/Autodesk/webdeploy/production/50d1a2b00ac928c7781cbca6551e586a5384d498/Api/Python/packages\adsk\fusion.py", line 7246, in _get_pointOnFace
    return _fusion.BRepFace__get_pointOnFace(self)
RuntimeError: 2 : InternalValidationError : face

**Comment by pludikar** [comment]
Hi @Kickjaw
How critical are the parametric dogbones to your model?  

If they're not essential, I would suggest that you use the static dogbone mode instead.  Unfortunately, the parametric calculations tend to be highly dependent on F360's internal model stability, and any face whose edges doesn't quite meet at all vertices (which can happen easily), or any other model mismatch, will throw a validation error, and there's not much the Addin can do about it.  Parametric dogbones tends to work well on simple models (perhaps with 8 - 10 dogbones), but anything a bit more complicated than that can start pushing the processing time up exponentially.

If you are willing to zip up your model and post it here  ( if you need help doing that, let me know), I can have a look at it and let you know specifically what has gone wrong.

FYI - I'm actually in the process of updating the dogbone Addin, and I have the basis of it working - however, F360 published an update to their API that includes customFeatures.  That was about a year ago.  This should have been a perfect feature set for my Addin, but when I started looking into it - it just doesn't work - it's riddled with bugs.  This feature, if it worked, would solve a significant number of problems, and would alleviate the need for static or parametric dogbone modes.  I'm inclined to wait for the F360 API team to get this fixed and officially released, but if it takes more than 3 or 4 months, I'll probably publish something in the interim.

Regards
Peter

**Comment by Kickjaw** [comment]
Hi, thanks for the quick response.  The static creation worked no problem. I could zip you the file if you want but it is a really simple model so I was confused as to why it did not work with parametric.

This is with the static dog bones in place.

![image](https://user-images.githubusercontent.com/28658404/160300095-0d031fc9-3258-4e65-b3a3-cf1f120dee0a.png)

**Comment by pludikar** [comment]
Hi @Kickjaw 

I just created a similar style model and it worked in parametric for me.  To be honest, I was expecting a more complex model, but the one you showed, should work fine in parametric.

What you could try is: 
add a sketch to the top face, 
insert a few points, 
then (outside the sketch again), 
open hole dialog (press H), 
select from sketch, 
and select the points
select settings and click OK

In principle, the holes should appear in your model, and this is the identical process to the one the Addin uses.  If you still get the error, then your model has corrupted - a "recalculate" can sometime clear the problem.

Also, make sure that there are actual edges that can be found!  If the static dogbones are still in place, that may also throw an error.

Here's my test model
[parametric model test.zip](https://github.com/DVE2000/Dogbone/files/8358474/parametric.model.test.zip)
