### ISSUE TITLE
New 2.2 version does not work.

### ISSUE THREAD

**Issue by buikpijn** [DVE2000/Dogbone#63]
Can run start from the plugin menu, plugin does start up, select a face on a model that requires dogbones, select the proper offsets, hit OK, but nothing. Nothing listed in the history line either.

After a restart of Fusion i need to press the 'start' button again, since it's not starting up automatically. (icons are not present, so the app is not running) Run on Startup is checked.

2.1 works just fine on the same model.

Tried clearing cache on Fusion, removed all other plugins. 2.2 simple doesn't work

**Comment by pludikar** [comment]
Hi,
I apologise for the delay in responding.  Unfortunately l suffered a bereavement of a very close family member just before Christmas, and I'm slowly getting back to picking up some outstanding tasks.

I know there was an issue with 2.2 and I thought I had fixed it.  I'll check again and get back to you shortly.

Peter

**Comment by buikpijn** [comment]
Arh! Peter, that’s horrible to hear. 

Lost my dad a few years back and a sister a longer time ago, These little routines you have (whatsapp him a picture of the family, of projects i’m working on).. It sure took a while. I heard an expression that sounded impossible at first, but you’re only able to enjoy the memories once you accepted the loss. It simple takes time before a smile turns up on your face remembering these precious moments. 

But while typing it my eyes start to water. 

Life is so fragile and brittle. Embrace the good moments with your family and make loads and loads of nice memories with each other. 

Take care! 

Rene

**Comment by pludikar** [comment]
Hi Rene,

Thanks for those words - It was actually my wife, so it's been a bit hard for the last few weeks.  I need to start getting back into keeping busy.

I've updated the latest version to 2.2.2 - There was an error caused by a cast that worked when I first published 2.2.1 but it was failing on me consistently.  Could you check it out and let me know if the issue still persists.

Peter

**Comment by buikpijn** [comment]
Peter.

That’s the worse nightmare. (we’re together since 1996, only been apart for a few days since then, most of my life i’ve been with her, it’s the love of my life, a true angel) I feel for you. Take all the time in the world you need. Do whatever it is that possibly makes you marginally happy again.  What a horrible situation to be in. 

I’ll test the new version.

Rene
