### ISSUE TITLE
Mortise Dogbone won't work

### ISSUE THREAD

**Issue by GastonTaiba** [DVE2000/Dogbone#65]
I´been trying to make mortise dogbone and it doesn't work in either of the directions, also nothing happens on the timeline.

**Comment by pludikar** [comment]
Hi,

Could you let me know if you have just installed this, or if the add-in was working before and has now stopped.

Regards
Peter
________________________________
From: GastonTaiba ***@***.***>
Sent: September 18, 2024 3:01 PM
To: DVE2000/Dogbone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DVE2000/Dogbone] Mortise Dogbone won't work (Issue #65)


I´been trying to make mortise dogbone and it doesn't work in either of the directions, also nothing happens on the timeline.

**Comment by pludikar** [comment]
Hi,

I've looked at the add-in, and I found a bug in the mortise mode and I've uploaded a new version to Github.  I believe I've fixed the problem, but please let me know if it still doesn't work

Regards
Peter
________________________________
