### ISSUE TITLE
Error on Obtuse or Acute angle detection

### ISSUE THREAD

**Issue by 3DTek-xyz** [DVE2000/Dogbone#67]
Hi Again
There is an error that pops up when you enable obtuse or acute angle detection.
<img width="860" alt="image" src="https://github.com/user-attachments/assets/32ac84d3-d58c-403e-a30e-ad995bb546ea">

**Comment by pludikar** [comment]
Hi Ben,

Just uploaded another version.  The error should now be fixed.  I obviously wasn't too diligent doing my regression testing when I changed from a parametric mode to being able to update the dogbones.  Sorry about that.  It's possible that they may be other bugs lurking - just let me know and I'll try and get them fixed

After all this I hope you still find the add-in useful 🙂

Peter
________________________________
From: 3DTek ***@***.***>
Sent: October 1, 2024 5:29 PM
To: DVE2000/Dogbone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DVE2000/Dogbone] Error on Obtuse or Acute angle detection (Issue #67)


Hi Again
There is an error that pops up when you enable obtuse or acute angle detection.
image.png (view on web)<https://github.com/user-attachments/assets/32ac84d3-d58c-403e-a30e-ad995bb546ea>

**Comment by pludikar** [comment]
Hi Ben,

Judging from one of the newer add-in examples, it looks like the add-in start up philosophy has changed in the last little while.  I need to absorb what they've done and then incorporate the changes.  It may require some rejigging how I get some of my global variables initialized. Hopefully it'll allow the add-in to initialize cleanly - there's currently an internalValidation Error on startup, which probably started happening when F360 upgraded the python version they use, and I didn't notice.

Peter
________________________________

**Comment by pludikar** [comment]
Hi Ben,
I appreciate this has taken a while, but I finally managed to get my hands on an apple machine.  The dogbone icons do appear on both the design and manufacturing workspaces with my last update.  However, it's important to note that the folder in the add-in folder can only have a-zA-Z0-9 characters in its name!  When you 1st add the addin using the  "+" in the Scripts and Add-ins dialog box - make sure the dogbone folder is named "dogbone" - no prefixes or suffixes (rename it if necessary).  Everything should work from now on.

Regards
Peter
________________________________
