### ISSUE TITLE
Dogbone fillet not created when selecting body

### ISSUE THREAD

**Issue by mipena** [DVE2000/Dogbone#8]
Using the commit 7e363bb doesn't work for me when selecting whole bodies, but does work when selecting edges. No error is displayed when performed on a body.

**Comment by Helmi** [comment]
Same for me. Sometimes nothing happens, sometimes i get an error that "no target body found to cut or intersect" even though i had a body selected with quite some inner 90° angles.

**Comment by caseycrogers** [comment]
Do you have your Fusion preferences set to "y-up" (the default)? At the moment I believe using y-up with dogbone causes problems. I'll push a modification that adds a toggle button in the interface to set y-up or z-up.

As a separate note, I strongly recommend you change your preferences to z-up. It's a far more prevalent standard than y-up (the entire additive manufacturing industry and vast majority of engineering). It annoys me to no end that Autodesk uses y-up by default, but it's an American standard so I suppose that's why Autodesk did it.

**Comment by caseycrogers** [comment]
I just pushed an update that supports y-up designs. Try downloading the latest version of Dogbone.py from github and replacing your existing copy of Dogbone.py with it. The new tool should have a "y-up" checkbox. Try turning the "y-up" checkbox on and tell me if that makes the dogbone fillets appear as you expect them to. Let me know if it fixes your problem!

I'm happy to support the default y-up setting, but I still STRONGLY encourage you to change the settings from the default to z-up just to make Fusion play nicer when importing and exporting files made in non-Autodesk software.

**Comment by Helmi** [comment]
I have never used Y up - so sorry, this couldn't be the reason for these errors. Y-up was the actual only default back in the days but as soon as they introduced Z-up I was happy enough not having to hack every design by rotating and resetting the home position.

So everything Z-up here.

**Comment by caseycrogers** [comment]
Glad to hear you're not using y-up.

If that's the case can you send me some screenshots of the inputs that are failing so I can try to replicate them and debug the problem?

Or better yet send me the .f3d file of the design that's failing?

**Comment by Helmi** [comment]
I'll try to pull out the version of my (rather big) assembly that caused the problem and see if i can just copy out that body to a new file for better research. I'll link it here as soon as I got it working.

**Comment by caseycrogers** [comment]
Thanks for helping me debug! I'd also love to see some renders of what you're working on, if you don't mind me sharing it on Twitter as an example of what my add-in is being used for (with proper attribution of course).

**Comment by mipena** [comment]
Hey Casey, thanks for addressing the problems we've been having. I first tried changing the preference to Z-up (I'm pretty new to this, so I didn't know about this option). I again had the same issue, selecting individual edges works, but not selecting the object. I then updated to the newest version of Dogbone and tried selecting the Y-up box with Y-up as the preferential modeling orientation as well as changing the orientation to Z-up without the Y-up box selected. Selecting the body did not work in either case, but it did produce an error with the Y-up box selected using the Z-up modeling orientation in the preferences ("Failed : startVertex" followed by "Error in Dogbone creation"). I tried attaching the .f3d file, but it's not an accepted file format. What's the best way to share the file with you? 
![image](https://cloud.githubusercontent.com/assets/13387663/12701091/379ffc3c-c7c3-11e5-9999-5906d926b7c9.png)

**Comment by caseycrogers** [comment]
Go ahead and e-mail the file to me at caseycrogers@berkeley.edu.

**Comment by caseycrogers** [comment]
@mipena Hey, sorry for the delay. I suspect your bug is related to one of the other reported issues for the API which I just fixed, can you try downloading the latest version of dogbone.py from github and replacing your current copy? Let me know if that fixes the problem.

**Comment by mipena** [comment]
I replaced the old Dogbone.py with the new version, and when I run the new version of Dogbone no new icons pop up in the toolbar. I was just supposed to replace the old file, correct?

**Comment by caseycrogers** [comment]
Yeah, just copy and paste the dogbone.py file and replace it. You shouldn't see any new icons. Once you've replaced the old dogbone, just go to scripts and add-ins, select dogbone, tell it to run. Find the dogbone icon under create and try it.

If the dogbone icon is no longer showing up with the latest version then that's a different problem.

**Comment by se7en9057** [comment]
sad to say mine isn't working either. not sure what i'm doing wrong. not getting any errors tho. perhaps user error. 

not using Yup
newest version of fusion
i downloaded the latest version, removed the py from my scripts inside fustion, then clicked plus, and added the version. i get the icon. but it doesnt work when selecting bodies or edges. object orientation is "top" or Z up facing

**Comment by JamieJEB** [comment]
I have problems as well.  I can't ever get it to work when I select the entire body.  But I can't get all the internal edges to work when I do each one individually.  Some work, but others say "no intersecting target body was found".  Is there something i'm doing wrong?  I'm on a mac, is that an issue?

**Comment by pludikar** [comment]
Hi @JamieJEB 

Oops! Sorry we haven't implemented select whole bodies/components yet.  We'll try to do that in the next release.  The issue is that by selecting the whole body, there's no obvious way to discover which way is up.  

Could you share your model on Fusion (you can PM me) , or save your model as an f3d (file|export in f360) then post it here.  The app will only recognise edges if they are right angles (for the moment - other angles are on the todo list).  So, once you select a primary face, you will be able to select edges associated with that face.  If you have a second tier face with edges, you have to select that face too (or as many faces as you have facing up.  

F360 has plenty of API issues associated with parametric, it sound like you are hitting some of them already.  Mirrored components are a particular issue.  If you are having issues with a component copy - then try selecting the faces and edges on the original component (there will be a :1 at the end of the name).  If that is still not working, please try and use static mode.  

Giving me as much information about what you are doing that causes the issue will be helpful.  

A debug log will also be helpful - In the app, you'll see at the bottom a tab for settings - go to Logging level and set debug.  Run the app for the model to recreate the problem.  In the Addin|Dogbone directory you'll find a log file - post it here.

Regards
Peter

**Comment by JamieJEB** [comment]
Peter, thank you so much for replying.  Uploaded the f3d file.  

When you mention mirror, I do use that when i create these things.  

So, I create the sketches, then create bodies, then create components and lay them out so I can cut them on my cnc machine.  Then I try and create the dogbones.  

I was unable to do anything with the logging.  I don't have that option in the settings deal.
[Emma Table v10.f3d.zip](https://github.com/DVE2000/Dogbone/files/2556173/Emma.Table.v10.f3d.zip)

**Comment by pludikar** [comment]
Hi,

I suspect that Fusion 360 has been updated and it's broken the parametric side of the dogbone app.

If you don't have a dialog box similar to this (below), then you also don't have the right version.  By opening up the settings tab, you will also get access to the debugging log setting.

[cid:79e539c2-658e-4411-90b5-68a2abacc6dd]

I will take a deeper look at the parametric issue, but it will probably take a little while.  Unless it's critical to have parametric dogbones, I'd suggest using the static mode instead.  That definitely works.

Regards
Peter


________________________________

**Comment by JamieJEB** [comment]
Thanks Peter, I don't think your picture is showing up.  I don't understand the difference between parametric dogbones and static.  I've only been using fusion for about 6 months.  I must be missing something here :)

**Comment by JamieJEB** [comment]
do you mean the right version of the dogbone addon?

**Comment by pludikar** [comment]
Hi,

Did you receive any emails after our last exchange?  I did respond, but I have a feeling that my email screwed up the response address.  

Peter

**Comment by pludikar** [comment]
Hi @JamieJEB,

In case this is a resend - I apologise.

I had a slightly deeper look at your model, and it's definitely a Fusion 360 bug.  

Try placing a hole on any of the components: select a face and then select extents|to and click on the opposing face.  It will throw an error - and that's F360!!

The screencast (here) shows a hole selection on the midshelf towards the end of the model construction.  The red highlight shows where the hole should cut and stop - It should have stopped on the selected face - that's the error.  The other components will show similar errors - often "zero distance".  It's a symptom of a poorly executed coordinate system in F360.

If you feel up to it - I'd suggest you report this on the forum.  The more independent voices AD hears the better it is.

The attached file shows you the embedded image that your Mac probably didn't render properly.
![dogbone dialog 1](https://user-images.githubusercontent.com/4363084/48318194-a9d0fb80-e5ca-11e8-9c8a-9530163b8084.png)

The difference between parametric and static is parametric moves when you change associated dimensions in the parameter dialog (accessed under modify - look for the capital sigma example here).  With parameters you can create a variable, such as "width" - give it a value and then when you create a sketch or a feature you can substitute the word "width" where you would normally type in a dimension.  Then, in the future you can change "width' in the parameter dialog and your model will follow suit.

On a further note.  I personally don't think there's anything wrong with the way you created your model, but F360 has a lot of quirks.  The internal Coordinate system is one of them.  You can minimize the issues you have by not converting bodies into components, but instead create the components you want early in your model construction, and then adding the bodies.  F360 is very sensitive to small errors, and creating bodies in components directly will help.

A slightly more robust work  flow is:
create empty components for midshelf, top, bottomshelf, front and back.
before you create a body for a component, hover your mouse over the component in the browser and you'll see a circle to the right of the entry - click on it.  That make the component active.  
In the active component create your sketches and bodies (via extrusions/pull etc)
make the next component active
and repeat

If you have component color cycling active (keyboard - shift N, or in "inspect menu" at the bottom of the drop down), it'll make it a little easier to see if you've mis-activated a component in the timeline.  If you experiment with it you'll see different colors in the timeline - your ideal goal is to keeps same colors together, although it's hard to keep everything consistent.

If you can't think of all the components at the start of the design, then wind back the timeline to a point where you created you created your empty components and then add a new component.

What I also do is create an assembly/component specifically for the nesting part of the workflow  ( eg call it "build").  In this process I would create, say, a table, which includes midshelf, top, bottomshelf, front and back components.  It's fully assembled and I want to keep it like that.  It'll be right when you click on the table assembly light bulb and the whole table disappears/appears.

Then, select all the components in the table (ie midshelf, top, bottomshelf, front and back) and paste them into the  build component.  Then you can nest the build components (ie flatten them for your cnc layout) - the original table build will remain intact! 

Hope that gives you a cleaner way of building models in Fusion

Peter

**Comment by DVE2000** [comment]
I did not. I sent you something last Wednesday, but figured you were busy skiing or skydiving or something. 🙂
